import Express from 'express'
const router = Express.Router()
import sendAPIResponse from '../../utils/api-response-wrapper'

router.get('/api/v1.1/features', (req, res) => {
  sendAPIResponse(res, {
    workshop_enabled: true,
    buildplates_enabled: true,
    enable_ruby_purchasing: false,
    commerce_enabled: true,
    full_logging_enabled: true,
    challenges_enabled: true,
    craftingv2_enabled: true,
    smeltingv2_enabled: true,
    inventory_item_boosts_enabled: true,
    player_health_enabled: true,
    minifigs_enabled: true,
    potions_enabled: true,
    social_link_share_enabled: true,
    social_link_launch_enabled: true,
    encoded_join_enabled: true,
    adventure_crystals_enabled: true,
    item_limits_enabled: true,
    adventure_crystals_ftue_enabled: true,
    expire_crystals_on_cleanup_enabled: true,
    challenges_v2_enabled: true,
    player_journal_enabled: true,
    player_stats_enabled: true,
    activity_log_enabled: true,
    seasons_enabled: true,
    daily_login_enabled: true,
    store_pdp_enabled: true,
    hotbar_stacksplitting_enabled: true,
    fancy_rewards_screen_enabled: true,
    async_ecs_dispatcher: true,
    adventure_oobe_enabled: true,
    tappable_oobe_enabled: true,
    map_permission_oobe_enabled: true,
    journal_oobe_enabled: true,
    freedom_oobe_enabled: true,
    challenge_oobe_enabled: true,
    level_rewards_v2_enabled: true,
    content_driven_season_assets: true,
    paid_earned_rubies_enabled: true
    /*workshop_enabled: true,
    buildplates_enabled: true,
    commerce_enabled: false,
    full_logging_enabled: true,
    challenges_enabled: true,
    craftingv2_enabled: true,
    smeltingv2_enabled: true,
    inventory_item_boosts_enabled: true,
    player_health_enabled: true,
    minifigs_enabled: true,
    potions_enabled: true,
    social_link_share_enabled: false,
    social_link_launch_enabled: false,
    encoded_join_enabled: true,
    adventure_crystals_enabled: true,
    item_limits_enabled: true,
    adventure_crystals_ftue_enabled: true,
    expire_crystals_on_cleanup_enabled: true,
    challenges_v2_enabled: true,
    player_journal_enabled: true,
    player_stats_enabled: true,
    activity_log_enabled: true,
    seasons_enabled: false,
    daily_login_enabled: true,
    store_pdp_enabled: true,
    hotbar_stacksplitting_enabled: true,
    fancy_rewards_screen_enabled: true,
    async_ecs_dispatcher: true,
    adventure_oobe_enabled: true,
    tappable_oobe_enabled: true,
    map_permission_oobe_enabled: true,
    journal_oobe_enabled: true,
    freedom_oobe_enabled: true,
    challenge_oobe_enabled: true,
    level_rewards_v2_enabled: true,
    content_driven_season_assets: false,
    paid_earned_rubies_enabled: true,
    enable_ruby_purchasing: false*/
  }, {})
})

router.get('/api/v1.1/settings', (req, res) => {
  sendAPIResponse(res, {
    encounterinteractionradius: 40,
    tappableinteractionradius: 70,
    tappablevisibleradius: -5,
    targetpossibletappables: 100,
    tile0: 10537,
    slowrequesttimeout: 2500,
    cullingradius: 50,
    commontapcount: 3,
    epictapcount: 7,
    speedwarningcooldown: 3600,
    mintappablesrequiredpertile: 22,
    targetactivetappables: 30,
    tappablecullingradius: 500,
    raretapcount: 5,
    requestwarningtimeout: 10000,
    speedwarningthreshold: 11.176,
    asaanchormaxplaneheightthreshold: 0.5,
    maxannouncementscount: 0,
    removethislater: 23,
    crystalslotcap: 3,
    crystaluncommonduration: 10,
    crystalrareduration: 10,
    crystalepicduration: 10,
    crystalcommonduration: 10,
    crystallegendaryduration: 10,
    maximumpersonaltimedchallenges: 3,
    maximumpersonalcontinuouschallenges: 3
  }, {})
})

export = router